import { StartsUsingParams, AbilityParams, AbilityFullParams, HeadMarkerParams, AddedCombatantParams, AddedCombatantFullParams, RemovingCombatantParams, GainsEffectParams, StatusEffectExplicitParams, LosesEffectParams, TetherParams, WasDefeatedParams, EchoParams, DialogParams, MessageParams, GameLogParams, GameNameLogParams, StatChangeParams, ChangeZoneParams, Network6dParams, NameToggleParams } from './netregexes';
import { Matches } from '../types/trigger';
export declare type MatchesStartsUsing = Matches<StartsUsingParams>;
export declare type MatchesAbility = Matches<AbilityParams>;
export declare type MatchesAbilityFull = Matches<AbilityFullParams>;
export declare type MatchesHeadMarker = Matches<HeadMarkerParams>;
export declare type MatchesAddedCombatant = Matches<AddedCombatantParams>;
export declare type MatchesAddedCombatantFull = Matches<AddedCombatantFullParams>;
export declare type MatchesRemovingCombatant = Matches<RemovingCombatantParams>;
export declare type MatchesGainsEffect = Matches<GainsEffectParams>;
export declare type MatchesStatusEffectExplicit = Matches<StatusEffectExplicitParams>;
export declare type MatchesLosesEffect = Matches<LosesEffectParams>;
export declare type MatchesTether = Matches<TetherParams>;
export declare type MatchesWasDefeated = Matches<WasDefeatedParams>;
export declare type MatchesEcho = Matches<EchoParams>;
export declare type MatchesDialog = Matches<DialogParams>;
export declare type MatchesMessage = Matches<MessageParams>;
export declare type MatchesGameLog = Matches<GameLogParams>;
export declare type MatchesGameNameLog = Matches<GameNameLogParams>;
export declare type MatchesStatChange = Matches<StatChangeParams>;
export declare type MatchesChangeZone = Matches<ChangeZoneParams>;
export declare type MatchesNetwork6d = Matches<Network6dParams>;
export declare type MatchesNameToggle = Matches<NameToggleParams>;
//# sourceMappingURL=matches.d.ts.map