export default class TimerBox extends HTMLElement {
    private _start;
    private _duration;
    rootElement: HTMLDivElement;
    largeBoxElement: HTMLDivElement;
    largeBoxBackgroundElement: HTMLDivElement;
    largeBoxForegroundElement: HTMLDivElement;
    smallBoxElement: HTMLDivElement;
    smallBoxBackgroundElement: HTMLDivElement;
    smallBoxForegroundElement: HTMLDivElement;
    timerElement: HTMLDivElement;
    readonly kLargeSize: number;
    readonly kSmallSize: number;
    readonly kBorderSize: number;
    readonly kFontSize: number;
    readonly kAnimateMS: number;
    private _threshold;
    private _bg;
    private _fg;
    private _scale;
    private _valueScale;
    private _towardTop;
    private _fill;
    private _hideAfter;
    private _bigAtZero;
    private _roundUpThreshold;
    private _connected;
    private _hideTimer;
    private _timer;
    private _animationFrame;
    static get observedAttributes(): string[];
    set duration(d: string | null);
    get duration(): string | null;
    set threshold(t: string | null);
    get threshold(): string | null;
    set scale(s: string | null);
    get scale(): string | null;
    set valuescale(s: string | null);
    get valuescale(): string | null;
    set bg(c: string | null);
    get bg(): string | null;
    set fg(c: string | null);
    get fg(): string | null;
    set toward(t: 'top' | 'bottom');
    get toward(): 'top' | 'bottom';
    set stylefill(s: 'fill' | 'empty' | null);
    get stylefill(): 'fill' | 'empty' | null;
    set hideafter(h: string | null);
    get hideafter(): string | null;
    set bigatzero(big: boolean);
    get bigatzero(): boolean;
    get value(): string;
    get elapsed(): string;
    set roundupthreshold(r: boolean);
    get roundupthreshold(): boolean;
    constructor();
    init(root: ShadowRoot): void;
    connectedCallback(): void;
    disconnectedCallback(): void;
    attributeChangedCallback(name: string, oldValue: string | number, newValue: string): void;
    layout(): void;
    draw(): void;
    reset(): void;
    advance(): void;
    show(): void;
    hide(): void;
}
//# sourceMappingURL=timerbox.d.ts.map