name: 解析插件
on:
  workflow_dispatch:
  push:
    paths:
      - 'parse/**'
      - '.github/workflows/parse.yml'
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/upload-artifact@v4
        with:
          name: ffxiv_act_plugin
          path: parse
          if-no-files-found: error
          compression-level: 9
