name: triggernometry
on:
  workflow_dispatch:
  push:
    paths:
      - 'triggernometry/**'
      - '.github/workflows/triggernometry.yml'
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')"
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/upload-artifact@v4
        with:
          name: triggernometry_${{ steps.date.outputs.date }}
          path: parse
          if-no-files-found: error
          compression-level: 9
